# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  servers = ["server1", "server2"]

  servers.each_with_index do |server, index|
    config.vm.define server do |server_config|
      server_config.vm.network "private_network", ip: "192.168.0.10#{index}"
      server_config.vm.hostname = server
      server_config.vm.provision "shell", path: "bootstrap.sh"
    end
  end
end
